const CartTypes = {
    INCREASE_ITEM_AMOUNT: 'INCREASE_ITEM_AMOUNT',
    DECREASE_ITEM_AMOUNT: 'DECREASE_ITEM_AMOUNT',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
}

export default CartTypes